"""Generate data/zzz_1.4/engines.json from the fairy database (source of truth).

Reads every W-engine modifier file under fairy's w_engines/ dir, maps each
display name → ZOD key via to_zod_key (with one override where the algorithm
diverges from fairy's canonical key), and validates every key against fairy's
canonical ZOD keyset (references/zo-allStat_gen.json["wengine"]).

Re-run whenever fairy adds an engine:  python tools/gen_engines.py

Source of truth: /root/fairy. Do not hand-edit data/zzz_1.4/engines.json.
"""
from __future__ import annotations

import glob
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from youkai_ocr.zod import to_zod_key  # noqa: E402

FAIRY = Path("/root/fairy")
W_ENGINES = FAIRY / "backend/app/data/modifiers/w_engines"
ZO_ALLSTAT = FAIRY / "references/zo-allStat_gen.json"
OUT = Path(__file__).parent.parent / "data/zzz_1.4/engines.json"

# to_zod_key diverges from fairy's canonical key only here: the hyphen in the
# "Fur-nace" pun yields "RoaringFurNace", but the canonical ZOD key is "RoaringFurnace".
KEY_OVERRIDES = {"Roaring Fur-nace": "RoaringFurnace"}

# Engines newer than zo-allStat_gen.json's keyset (that reference is slightly stale).
# Their to_zod_key output is trusted; listed so unexpected key drift still hard-errors.
NEWER_THAN_REF = {
    "Frostfall Sickle", "Neon Fantasies", "Serpentine Seeker",
    "Starlight Rider Faceplate", "The Simmering Pot",
}


def main() -> None:
    ref_keys = set(json.loads(ZO_ALLSTAT.read_text())["wengine"].keys())

    # name -> (key, rarity)
    engines: dict[str, tuple[str, str]] = {}
    for f in sorted(glob.glob(str(W_ENGINES / "*.json"))):
        d = json.loads(Path(f).read_text())
        name = d["source_name"]
        rarity = d["rarity"]
        key = KEY_OVERRIDES.get(name, to_zod_key(name))
        if key not in ref_keys and name not in NEWER_THAN_REF:
            raise SystemExit(
                f"ERROR: key {key!r} for {name!r} not in fairy canonical keyset "
                f"and not in NEWER_THAN_REF allowlist. Resolve before generating."
            )
        engines[name] = (key, rarity)

    # Group: S, A, B (non-bracket), B (bracket series). Alpha within group.
    groups: dict[str, list[str]] = {"S": [], "A": [], "B": [], "Bb": []}
    for name in sorted(engines, key=str.lower):
        _, rarity = engines[name]
        if rarity == "B":
            groups["Bb" if name.startswith("[") else "B"].append(name)
        else:
            groups[rarity].append(name)

    blocks = [
        ("_comment_s_rank", "--- S-rank (signature / limited / standard gacha) ---", groups["S"]),
        ("_comment_a_rank", "--- A-rank ---", groups["A"]),
        ("_comment_b_rank", "--- B-rank ---", groups["B"]),
        ("_comment_b_rank_series", "--- B-rank bracket series (standard pool) ---", groups["Bb"]),
    ]

    # Hand-format to preserve _comment sentinels + blank-line group separators.
    lines = ["{", '  "_meta": {', '    "game_version": "1.4",']
    lines.append(
        '    "description": "ZZZ W-Engine display names (English PC client) → ZOD key. '
        "GENERATED by tools/gen_engines.py from /root/fairy (source of truth) — do not hand-edit. "
        'Grouped by rarity for readability; grouping has no semantic effect.",'
    )
    lines.append(f'    "last_updated": "{date.today().isoformat()}"')
    lines.append("  },")
    lines.append('  "engines": {')

    body: list[str] = []
    for comment_key, comment_val, names in blocks:
        seg = [f'    "{comment_key}": "{comment_val}",']
        for name in names:
            key = engines[name][0]
            seg.append(f'    {json.dumps(name)}: {json.dumps(key)},')
        body.append("\n".join(seg))
    joined = "\n\n".join(body)
    joined = joined.rstrip(",")  # last entry must not have a trailing comma
    lines.append(joined)
    lines.append("  }")
    lines.append("}")

    OUT.write_text("\n".join(lines) + "\n")

    total = sum(len(g) for g in groups.values())
    print(f"Wrote {OUT} — {total} engines "
          f"(S={len(groups['S'])}, A={len(groups['A'])}, "
          f"B={len(groups['B'])}, B-series={len(groups['Bb'])})")


if __name__ == "__main__":
    main()
